// oxdump/output/dump_cs.cpp — генерация dump.cs.
//
// Калька с generators.py::gen_dump_cs. Формат совместим с Il2CppDumper: дерево
// классов, у каждого — блок полей (сперва статические, потом обычные) и блок
// методов с RVA. Порядок и разделители держим точь-в-точь, иначе привычные
// грепы и диффы против эталонного дампа перестанут работать.
#include "oxdump/output/generators.h"
#include "oxdump/analysis/xref.h"
#include <sstream>

namespace oxdump::output {

namespace {

// TypeAttributes: биты вида типа. Совпадают со значениями из generators.py.
constexpr u32 TYPE_ATTR_INTERFACE = 0x20;
constexpr u32 TYPE_ATTR_ABSTRACT  = 0x80;
constexpr u32 TYPE_ATTR_SEALED    = 0x100;

// Экранирует строку-подсказку для комментария: убирает кавычки и любые
// не-печатные символы, чтобы `// ~ "..."` не разъехался. Фильтр в xref уже
// оставляет только печатный ASCII, но кавычку внутри строки всё равно гасим.
std::string escape_hint(const std::string& s) {
    std::string o;
    o.reserve(s.size());
    for (char c : s) {
        if (c == '"' || c == '\\') o += '\'';
        else if (c == '\n' || c == '\r' || c == '\t') o += ' ';
        else o += c;
    }
    return o;
}

} // namespace

std::string gen_dump_cs(model::Model& m, const progress_cb& progress,
                        const model::GenericInstanceTable* gt) {
    auto& L = m.layout();
    const u32 total = L.typedef_count;
    const bool have_generics = gt && gt->loaded();
    // Сколько конкретных инстанциаций перечислять в комментарии над классом:
    // у популярных дженериков их сотни, а строку хочется держать читаемой.
    constexpr std::size_t MAX_INST_LIST = 8;

    // Резервируем с запасом: дамп на этой сборке ~25 МБ. Одна большая строка
    // с += быстрее, чем список строк + join — меньше аллокаций.
    std::string out;
    out.reserve(32u * 1024u * 1024u);
    out += "// Generated by OxideDumper\n\n";

    for (u32 i = 0; i < total; ++i) {
        if (progress && i % 2000 == 0) progress(i, total);

        const std::string name = m.td_name(i);
        if (name.empty()) continue;
        const std::string ns = m.td_namespace(i);
        const u32 flags = m.td_u32(i, m.td_layout().flags) & 0xFFFF;

        const bool is_iface = (flags & TYPE_ATTR_INTERFACE) != 0;
        const char* kind = is_iface ? "interface" : "class";

        // Базовый тип: печатаем, только если не object/System.Object.
        std::string parent;
        const s32 parent_idx = m.td_s32(i, m.td_layout().parent);
        if (parent_idx >= 0) {
            const u64 pva = m.type_va(parent_idx);
            if (pva) {
                const std::string pn = m.type_name(pva);
                if (pn != "object" && pn != "System.Object") parent = " : " + pn;
            }
        }

        // Комментарий с конкретными инстанциациями этого generic-класса
        // (List<int>, List<string>, ...). Только если таблица построена и у
        // типа есть инстансы. Список ограничен MAX_INST_LIST, остаток свёрнут
        // в «(+N more)», чтобы у List/Dictionary строка не разрасталась.
        if (have_generics) {
            std::vector<const model::GenericInstance*> inst = gt->instances_of(i);
            if (!inst.empty()) {
                out += "// " + std::to_string(inst.size()) + " instances: ";
                const std::size_t lim = std::min(inst.size(), MAX_INST_LIST);
                for (std::size_t k = 0; k < lim; ++k) {
                    if (k) out += ", ";
                    out += inst[k]->display_name;
                }
                if (inst.size() > lim)
                    out += ", (+" + std::to_string(inst.size() - lim) + " more)";
                out += "\n";
            }
        }

        out += "// Namespace: ";
        out += ns;
        out += "\n";

        // Модификаторы: public, затем abstract/sealed (только у классов).
        out += "public";
        if (!is_iface) {
            if (flags & TYPE_ATTR_ABSTRACT) out += " abstract";
            if (flags & TYPE_ATTR_SEALED)   out += " sealed";
        }
        out += " ";
        out += kind;
        out += " ";
        out += name;
        out += parent;
        out += " // TypeDefIndex: ";
        out += std::to_string(i);
        out += "\n{\n";

        // ── поля ──────────────────────────────────────────────────────────
        std::vector<model::Field> fields = m.fields_of(i);
        if (!fields.empty()) {
            out += "\t// Fields\n";
            // Сперва статические — у них своя нумерация смещений, вперемешку
            // с обычными это сбивало бы с толку (так же делает Il2CppDumper).
            for (const auto& f : fields) {
                if (!f.is_static) continue;
                out += "\tpublic static " + f.type_name + " " + f.name +
                       "; // " + hex(f.offset) + "\n";
            }
            for (const auto& f : fields) {
                if (f.is_static) continue;
                out += "\tpublic " + f.type_name + " " + f.name +
                       "; // " + hex(f.offset) + "\n";
            }
            out += "\n";
        }

        // ── методы ────────────────────────────────────────────────────────
        std::vector<model::Method> methods = m.methods_of(i);
        if (!methods.empty()) {
            out += "\t// Methods\n";
            for (std::size_t mi = 0; mi < methods.size(); ++mi) {
                const auto& mo = methods[mi];
                std::vector<model::Param> params =
                    m.params_of(mo.param_start, mo.param_count);
                std::string sig;
                for (std::size_t k = 0; k < params.size(); ++k) {
                    if (k) sig += ", ";
                    sig += params[k].type_name + " " + params[k].name;
                }
                // RVA: 0 у методов не из основной сборки — как в эталоне, "-1".
                if (mo.rva) out += "\t// RVA: " + hex(mo.rva) + "\n";
                else        out += "\t// RVA: -1\n";
                out += "\tpublic " + mo.ret_type + " " + mo.name + "(" + sig +
                       ") { }";
                // HINT-колонка: если для этого обфусцированного метода нашёлся
                // строковый литерал (--xref-names), дописываем его комментарием.
                // Без флага lookup_hint пуст — строка ниже добавляет только "\n\n",
                // вывод остаётся прежним.
                const std::string& hint =
                    analysis::lookup_hint(i, static_cast<u32>(mi));
                if (!hint.empty())
                    out += "  // ~ \"" + escape_hint(hint) + "\"";
                out += "\n\n";
            }
        }

        out += "}\n";
    }

    if (progress) progress(total, total);
    return out;
}

} // namespace oxdump::output
