// oxdump/output/il2cpp_h.cpp — генерация il2cpp.h.
//
// Формат совместим с Il2CppDumper: одна C-структура на тип со смещениями полей.
// Имя структуры — по КОРОТКОМУ имени класса (PlayerManager_o), а не полному с
// namespace: так заголовок совпадает с тем, что ждут привычные инструменты, и
// имена не разбухают Oxide_Features_...  Коллизии коротких имён здесь осознанно
// приняты — как и в Il2CppDumper.
//
// Раскладка объекта повторяет рантайм: в начале всякого Il2CppObject лежат
// void* klass и MonitorData* monitor, дальше — поля экземпляра.
#include "oxdump/output/generators.h"
#include <sstream>

namespace oxdump::output {

namespace {

// Идентификатор, пригодный для C: не-[A-Za-z0-9_] заменяем на '_', ведущую
// цифру префиксуем подчёркиванием. Калька с generators.py::_sanitize.
std::string sanitize(const std::string& name) {
    std::string s;
    s.reserve(name.size());
    for (char ch : name) {
        const bool ok = (ch >= 'A' && ch <= 'Z') || (ch >= 'a' && ch <= 'z') ||
                        (ch >= '0' && ch <= '9') || ch == '_';
        s += ok ? ch : '_';
    }
    if (s.empty() || (s[0] >= '0' && s[0] <= '9')) s = "_" + s;
    return s;
}

// Тип C# -> его представление в il2cpp.h. Калька с generators.py::_c_type.
std::string c_type(const std::string& t) {
    // Примитивы по точному совпадению.
    struct P { const char* cs; const char* c; };
    static const P prim[] = {
        {"bool", "bool"}, {"char", "uint16_t"}, {"sbyte", "int8_t"},
        {"byte", "uint8_t"}, {"short", "int16_t"}, {"ushort", "uint16_t"},
        {"int", "int32_t"}, {"uint", "uint32_t"}, {"long", "int64_t"},
        {"ulong", "uint64_t"}, {"float", "float"}, {"double", "double"},
        {"IntPtr", "intptr_t"}, {"UIntPtr", "uintptr_t"}, {"void", "void"},
    };
    for (const P& p : prim) if (t == p.cs) return p.c;
    if (t == "string") return "String_o*";
    // Массивы и generic — непрозрачные указатели: их точная раскладка тут не
    // нужна, а разворачивать её значило бы тянуть весь граф типов.
    if ((t.size() >= 2 && t.compare(t.size() - 2, 2, "[]") == 0) ||
        t.find('<') != std::string::npos) {
        return "void*";
    }
    return sanitize(t) + "_o*";
}

} // namespace

std::string gen_il2cpp_h(model::Model& m, const progress_cb& progress) {
    auto& L = m.layout();
    const u32 total = L.typedef_count;

    std::string out;
    out.reserve(16u * 1024u * 1024u);
    out += "// Generated by OxideDumper\n#pragma once\n\n";

    for (u32 i = 0; i < total; ++i) {
        if (progress && i % 2000 == 0) progress(i, total);

        const std::string name = m.td_name(i);
        if (name.empty()) continue;
        std::vector<model::Field> fields = m.fields_of(i);
        if (fields.empty()) continue;

        const std::string sym = sanitize(name);

        // Статические поля живут в отдельном блоке static_fields и нумеруются
        // с нуля. Смешивать с обычными нельзя — смещения пойдут вразнобой.
        std::string inst, stat;
        bool have_inst = false, have_stat = false;
        for (const auto& f : fields) {
            const std::string line = "\t" + c_type(f.type_name) + " " +
                                     sanitize(f.name) + "; // " + hex(f.offset) +
                                     "\n";
            if (f.is_static) { stat += line; have_stat = true; }
            else             { inst += line; have_inst = true; }
        }
        if (!have_inst && !have_stat) continue;

        out += "struct " + sym + "_Fields {\n" + inst + "};\n";
        if (have_stat) {
            out += "struct " + sym + "_StaticFields {\n" + stat + "};\n";
        }
        // Раскладка объекта: заголовок Il2CppObject + поля экземпляра.
        out += "struct " + sym + "_o {\n";
        out += "\tvoid* klass;\n";
        out += "\tMonitorData* monitor;\n";
        out += "\t" + sym + "_Fields fields;\n";
        out += "};\n";
    }

    if (progress) progress(total, total);
    return out;
}

} // namespace oxdump::output
