// oxdump/output/structs_h.cpp — генерация structs.h.
//
// Обычный C-заголовок с рантайм-структурами IL2CPP: Il2CppObject и то, что на
// нём стоит (Il2CppClass, Il2CppString, Il2CppArray, MonitorData, VirtualInvoke
// и т.п.). Il2CppDumper такого файла не даёт — а без него, разобрав библиотеку
// в IDA/Ghidra, каждый раз приходится вручную вводить хотя бы заголовок объекта
// (klass + monitor), чтобы поля экземпляра встали на свои смещения.
//
// Файл целиком статический — из Model берётся только баннер (версия/дата).
// Требования к содержимому жёсткие: он должен компилироваться `gcc -c -x c`
// (то есть быть валидным C89/C99, а не C++). Поэтому:
//   * все типы через <stdint.h> (int32_t, uint16_t, uintptr_t);
//   * никаких bool/nullptr/пространств имён;
//   * гибкий массив (chars[]) — это C99, gcc его принимает;
//   * порядок объявлений — с учётом предварительных (forward) typedef'ов, чтобы
//     взаимные ссылки (класс ссылается на класс, объект — на класс) собрались.
//
// Раскладка полей повторяет рантайм Unity IL2CPP (metadata v24.x–v29/v31). Часть
// полей Il2CppClass опущена сознательно: приведены только те, до которых обычно
// доходят руки при реверсе (имя/namespace/образ/родитель/размеры/токены). Полная
// раскладка класса меняется от версии к версии и здесь не нужна.
#include "oxdump/output/generators.h"
#include <ctime>

namespace oxdump::output {

namespace {

// Дата сборки в формате YYYY-MM-DD — для баннера. Локальное время: файл
// потребляет человек, а не машина, поэтому UTC-строгость не нужна.
std::string today() {
    std::time_t t = std::time(nullptr);
    std::tm tm{};
#if defined(_WIN32)
    localtime_s(&tm, &t);
#else
    localtime_r(&t, &tm);
#endif
    char buf[32];
    std::snprintf(buf, sizeof(buf), "%04d-%02d-%02d",
                  tm.tm_year + 1900, tm.tm_mon + 1, tm.tm_mday);
    return std::string(buf);
}

} // namespace

std::string gen_structs_h(model::Model& m) {
    const u32 types = static_cast<u32>(m.types_count());

    std::string out;
    out.reserve(8192);

    // ── шапка: как импортировать ────────────────────────────────────────────
    out +=
        "// ============================================================================\n"
        "// structs.h — runtime IL2CPP struct definitions for IDA Pro / Ghidra\n"
        "// Generated by OxideDumper 1.0.0 (C++17)\n"
        "// Date: " + today() + "\n"
        "// Types in this image: " + thousands(types) + "\n"
        "// ============================================================================\n"
        "//\n"
        "// HOW TO IMPORT\n"
        "// -------------\n"
        "//   IDA Pro : File -> Load file -> Parse C header file...  (select this file)\n"
        "//             Then Shift+F1 (Local Types) shows Il2CppObject, Il2CppString, ...\n"
        "//   Ghidra  : File -> Parse C Source...  (add this file, then Parse)\n"
        "//             Types appear under the program's Data Type Manager.\n"
        "//\n"
        "// These are the headers every managed object shares. After importing, apply\n"
        "// Il2CppObject at the start of any instance to line up klass + monitor, then\n"
        "// the per-class *_o structs from il2cpp.h drop their fields at the right offset.\n"
        "//\n"
        "// Layout matches the Unity IL2CPP runtime (metadata v24.x through v29/v31) for\n"
        "// the fields reverse engineers actually reach. Il2CppClass is intentionally\n"
        "// partial: its full layout shifts between versions and is not needed here.\n"
        "// ============================================================================\n"
        "\n"
        "#ifndef OXDUMP_IL2CPP_STRUCTS_H\n"
        "#define OXDUMP_IL2CPP_STRUCTS_H\n"
        "\n"
        "#include <stdint.h>\n"
        "\n";

    // ── forward-объявления ──────────────────────────────────────────────────
    // Il2CppObject ссылается на Il2CppClass; массивы — на Il2CppArrayBounds.
    // Даём typedef'ы вперёд, чтобы взаимные ссылки собрались в любом порядке.
    out +=
        "// ---- forward declarations (mutually referencing types) ----\n"
        "typedef struct Il2CppClass        Il2CppClass;\n"
        "typedef struct Il2CppType         Il2CppType;\n"
        "typedef struct Il2CppImage        Il2CppImage;\n"
        "typedef struct MethodInfo         MethodInfo;\n"
        "typedef struct Il2CppObject       Il2CppObject;\n"
        "typedef struct Il2CppArrayBounds  Il2CppArrayBounds;\n"
        "\n";

    // ── MonitorData / заголовок объекта ─────────────────────────────────────
    out +=
        "// ---- object monitor (lazy lock word; opaque here) ----\n"
        "typedef struct MonitorData MonitorData;\n"
        "\n"
        "// ---- Il2CppObject: the 2-pointer header at the start of EVERY managed object ----\n"
        "// klass    -> Il2CppClass* describing this object's type (vtable, fields, ...)\n"
        "// monitor  -> lazily-allocated lock word for lock(){}/Monitor.Enter\n"
        "struct Il2CppObject {\n"
        "    Il2CppClass  *klass;\n"
        "    MonitorData  *monitor;\n"
        "};\n"
        "\n";

    // ── Il2CppClass (частично) ──────────────────────────────────────────────
    // Порядок первых полей (image, gc_desc, name, namespaze, byval_type ...)
    // соответствует рантайму; дальше — только избранные размеры/токены, чтобы
    // при реверсе можно было адресоваться по имени, а не по «поле в +0x..».
    out +=
        "// ---- Il2CppClass (PARTIAL): the fields most useful when reversing ----\n"
        "// Only the leading, version-stable fields are named; the rest of the runtime\n"
        "// layout (vtable slots, interface offsets, cctor state, ...) is elided.\n"
        "struct Il2CppClass {\n"
        "    Il2CppImage  *image;         // owning image (assembly)\n"
        "    void         *gc_desc;       // GC descriptor\n"
        "    const char   *name;          // type name, e.g. \"PlayerManager\"\n"
        "    const char   *namespaze;     // namespace (\"namespace\" is a C++ keyword)\n"
        "    Il2CppType   *byval_type;    // Il2CppType* for value-passing of this type\n"
        "    Il2CppType   *this_type;     // Il2CppType* for by-ref of this type\n"
        "    Il2CppClass  *element_class; // for arrays/pointers: element type\n"
        "    Il2CppClass  *cast_class;    // class used for cast checks\n"
        "    Il2CppClass  *declaring_type;// enclosing type for nested classes\n"
        "    Il2CppClass  *parent;        // base class\n"
        "    void         *generic_class; // Il2CppGenericClass* if generic instance\n"
        "    void         *type_metadata_handle;\n"
        "    void         *interop_data;\n"
        "    Il2CppClass  *klass;         // self-pointer (runtime bookkeeping)\n"
        "    void         *fields;        // FieldInfo* array (fields_size entries)\n"
        "    void         *events;        // EventInfo*\n"
        "    void         *properties;    // PropertyInfo*\n"
        "    const MethodInfo **methods;  // MethodInfo* array (methods_size entries)\n"
        "    void         *nestedTypes;   // Il2CppClass** array\n"
        "    void         *implementedInterfaces;\n"
        "    void         *interfaceOffsets;\n"
        "    void         *static_fields; // block holding this class's static fields\n"
        "    void         *rgctx_data;\n"
        "    void         *typeHierarchy; // Il2CppClass** up the parent chain\n"
        "    void         *unity_user_data;\n"
        "    uint32_t      initializationExceptionGCHandle;\n"
        "    uint32_t      cctor_started;\n"
        "    uint32_t      cctor_finished_or_no_cctor;\n"
        "    uint32_t      token;         // metadata token of this type\n"
        "    int32_t       instance_size; // sizeof an instance (bytes)\n"
        "    int32_t       actualSize;\n"
        "    int32_t       element_size;  // for arrays: sizeof(element)\n"
        "    int32_t       native_size;\n"
        "    uint32_t      static_fields_size;\n"
        "    uint32_t      thread_static_fields_size;\n"
        "    int32_t       thread_static_fields_offset;\n"
        "    uint32_t      flags;         // TypeAttributes\n"
        "    uint16_t      fields_size;   // number of instance+static fields\n"
        "    uint16_t      methods_size;  // number of methods\n"
        "    uint16_t      property_count;\n"
        "    uint16_t      event_count;\n"
        "    uint16_t      nested_type_count;\n"
        "    uint16_t      vtable_count;\n"
        "    uint16_t      interfaces_count;\n"
        "    uint16_t      interface_offsets_count;\n"
        "};\n"
        "\n";

    // ── Il2CppString ────────────────────────────────────────────────────────
    // Заголовок объекта встроен полем object (не наследование — в C наследования
    // нет). length + гибкий массив UTF-16, ровно как в рантайме.
    out +=
        "// ---- Il2CppString: a boxed System.String ----\n"
        "// object.klass points at the String class; chars[] is UTF-16, NOT null padded\n"
        "// by length (there is a trailing L'\\0' at chars[length] the runtime keeps).\n"
        "struct Il2CppString {\n"
        "    Il2CppObject  object;   // shared 2-pointer header\n"
        "    int32_t       length;   // number of UTF-16 code units\n"
        "    uint16_t      chars[];  // UTF-16 data (flexible array member, C99)\n"
        "};\n"
        "typedef struct Il2CppString Il2CppString;\n"
        "\n";

    // ── Il2CppArray ─────────────────────────────────────────────────────────
    // Однорангового массива хватает для реверса: bounds==NULL и max_length —
    // длина. Для многомерных bounds указывает на массив Il2CppArrayBounds.
    out +=
        "// ---- Il2CppArrayBounds: per-dimension length/lower-bound (multidim arrays) ----\n"
        "struct Il2CppArrayBounds {\n"
        "    uintptr_t length;        // element count in this dimension\n"
        "    int32_t   lower_bound;   // usually 0\n"
        "};\n"
        "\n"
        "// ---- Il2CppArray: a boxed managed array (T[]) ----\n"
        "// For a plain single-dimension array bounds == NULL and max_length is the\n"
        "// element count. Element data follows this header in memory (vector[]).\n"
        "struct Il2CppArray {\n"
        "    Il2CppObject       object;      // shared 2-pointer header\n"
        "    Il2CppArrayBounds *bounds;      // NULL for single-dimension arrays\n"
        "    uintptr_t          max_length;  // total element count\n"
        "    void              *vector[];    // element storage (flexible array member)\n"
        "};\n"
        "typedef struct Il2CppArray Il2CppArray;\n"
        "\n";

    out += "#endif /* OXDUMP_IL2CPP_STRUCTS_H */\n";
    return out;
}

} // namespace oxdump::output
